config/routes.rb
Spont::Application.routes.draw do
  
  root :to => "projects#index"

  resources :projects do 
      resources :comments
    end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

belongs_to :user

has_many :comments, dependent: :destroy



	
end

app/models/user.rb
class User < ActiveRecord::Base
include Clearance::User
	
	has_many :projects

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



 def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to project_path(@project)

  end




end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


# Setting the project by finding it only for these actions
	before_action :set_project, only: [:show, :edit, :update, :destroy]
# Authorizing so no access
	before_filter :authorize
# Making sure creator only can edit
	before_action :editable?, only: [:edit, :destroy]
# Make sure a user can view his own projects only
	before_action :can_view?, only: [:show]

def index
	@p = Project.where(user_id: current_user)
end


def new
	@project = Project.new
end

def create
	@project = Project.new(project_params)
#Pass the user id to the project as it is created	
	@project.user_id = current_user.id
		if @project.save
			redirect_to @project
			flash[:notice] = "Project has been created!"
		else
			render 'new'
		end
end


def show	
end

def edit
end

def update
	if @project.update(project_params)
		redirect_to @project
		flash[:notice] = "Project was updated, thank you."
	else
		render 'edit'
	end

end

def destroy
	@project.destroy
	redirect_to root
	
end


private

	def editable?
		@p = @project.user_id
		@u = current_user.id

		if @p == @u
			render 'edit'

		else
		flash[:notice] = "Can't edit this!"
			 render 'public/500'
		end
	end



	def can_view?
		if @project.user_id == current_user.id
			

		else
			render 'public/404'
			flash[:notice] = "Can't view this"
		end
	end


	def set_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:name, :description, :budget, :user, :category_of_work, :approval)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_meeting_room.html.erb
<h2>Comments</h2>
<% @project.comments.order('created_at DESC').each do |comment| %>
  <p>
    <strong>Comment by: </strong><%= comment.commenter %>
 
	<strong>Comment: </strong><%= comment.body %>
  </p>

<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@project, @project.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/_show.html.erb
<h2>Comments</h2>
<% @project.comments.order('created_at DESC').each do |comment| %>
  <p>
    <strong>Comment by: </strong><%= comment.commenter %>
 
	<strong>Comment: </strong><%= comment.body %>
  </p>

<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@project, @project.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_clearance.html.erb
<div class="navbar">
 <% if signed_in? %>
      Signed in as: <%= current_user.email %> {id:<%= current_user.id %>}
      <%= link_to 'Sign out', sign_out_path, :method => :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
    ||

    <%= link_to "Projects", projects_path %>


    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spont</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/clearance' %>
<%= yield %>

</body>
</html>

app/views/projects/_details.html.erb
<p>
	<%= @project.budget %>
	<%= @project.category_of_work  %>

<% if @project.approval %>
	<p>Project is approved!</p>
<% else %>
	<p>Project hasn't been approved yet</p> 

<% end %>

</p>

app/views/projects/_form.html.erb
<%=  simple_form_for @project do |f| %>
	


	<%= f.input :name %>
	<%= f.input :description %>


	
<% @b = ['500', '2,500', '5,000', '10,000'] %>
<% @b[0] = 500 %>
<% @b[1] = 2500 %>
<% @b[2] = 5000 %>
<% @b[3] = 10000 %>


	<%= f.select :budget, Around: @b %>







<% @cow1 = ["Web Design" ,"Web Development" ] %>	
<% @cow2 = ["Logo", "Branding", "Graphics"]%>
	
	<p>Work type<%= f.select :category_of_work, Web: @cow1, Design: @cow2 %></p>

	
	<% f.input :user_id %>

<%= f.input :approval %>



	<%= f.button :submit %>


	<% end %>

app/views/projects/edit.html.erb
<h2>Editing <%= @project.name %></h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<% for p in @p  %>
	<h3><%= p.name %></h3>
	<p><%= p.description %></p>
		<p>Created by user #<%= p.user_id %></p>

<% end %>

app/views/projects/new.html.erb
<h2>Create a new project</h2>


<%= render 'form' %>

app/views/projects/show.html.erb
<h3><%= @project.name %></h3>
<p><%= @project.description %></p>
<p><%= @project.budget %></p>

<% if @project.approval %>
	<p>Project has been approved!</p>
<% else %>
	<p>Project is not yet approved!</p>
<% end %>



	<%= render 'comments/meeting_room' %>


<h5>Created By: User <%= @project.user_id %>
|| || || || 
Logged in  User is: <%= current_user.id %></h5>

app/views/users/_form.html.erb
<div class='text-field'>
  <%= f.input :email %>
</div>

<div class='password-field'>
 <%= f.input :password %>
</div>

app/views/users/new.html.erb
<div id='clearance' class='sign-up'>
  <h2>Sign up</h2>

<%= simple_form_for @user do |f| %>
  
  <div class='text-field'>
  <%= f.input :email %>
</div>

<div class='password-field'>
 <%= f.input :password %>
</div>




<div class='submit-field'>
  <%= f.button :submit %>
</div>
 <div class='other-links'>
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>

  <% end %>
</div>